# Generated by Django 5.2.17 on 2026-10-02 12:40

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'panier',
                'verbose_name_plural': 'paniers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('shipping', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('returned', 'Retournée')], default='pending', max_length=12)),
                ('recipient', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('quarter', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('cash', 'Cash à la livraison')], max_length=16)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancel_reason', models.CharField(blank=True, choices=[('changed_mind', 'changed_mind'), ('ordered_by_mistake', 'ordered_by_mistake'), ('too_slow', 'too_slow'), ('cheaper_elsewhere', 'cheaper_elsewhere'), ('other', 'other')], max_length=24)),
                ('cancel_details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant_label', models.CharField(blank=True, max_length=255)),
                ('product_image', models.URLField(blank=True, max_length=500)),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('shipping', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('returned', 'Retournée')], max_length=12)),
                ('to_status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('shipping', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('returned', 'Retournée')], max_length=12)),
                ('actor_role', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='orders_cart_item_unique', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orders_cart_item_quantity_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='orders_order_client'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_reseller', 'status'], name='orders_order_reseller'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('shipping_fee')))), name='orders_order_total_consistent'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orders_item_quantity_positive'),
        ),
    ]
