# Generated by Django 5.2.17 on 2026-10-02 11:29

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="adresse e-mail"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?[\\d\\s().-]{7,20}$")
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                ("avatar", models.URLField(blank=True, max_length=500, verbose_name="photo")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("reseller", "Revendeur"),
                            ("manager", "Responsable"),
                            ("admin", "Administrateur"),
                        ],
                        db_index=True,
                        default="client",
                        max_length=16,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^\\d{4}$")],
                        verbose_name="code revendeur",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("online", "En ligne"),
                            ("away", "Absent"),
                            ("offline", "Hors ligne"),
                        ],
                        default="offline",
                        max_length=8,
                        verbose_name="disponibilité",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.070"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("0.500")),
                        ],
                        verbose_name="taux de commission",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vu pour la dernière fois"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invité par",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_resellers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("home", "Domicile"),
                            ("office", "Bureau"),
                            ("family", "Famille"),
                            ("other", "Autre"),
                        ],
                        default="home",
                        max_length=8,
                    ),
                ),
                ("recipient", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("line1", models.CharField(max_length=255)),
                ("quarter", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=80)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "adresse",
                "verbose_name_plural": "adresses",
                "ordering": ("-is_default", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("preferences", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "préférences de notification",
                "verbose_name_plural": "préférences de notification",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="accounts_user_email_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commission_rate__gte", 0), ("commission_rate__lte", Decimal("0.500"))
                ),
                name="accounts_user_commission_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="accounts_address_single_default",
            ),
        ),
    ]
