# Generated by Django 5.2.17 on 2026-10-02 20:50

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('link_label', models.CharField(blank=True, max_length=60)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'bannière',
                'verbose_name_plural': 'bannières',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=60)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'question fréquente',
                'verbose_name_plural': 'questions fréquentes',
                'ordering': ('category', 'position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('position', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_cdf', models.DecimalField(decimal_places=2, default=Decimal('2800.00'), max_digits=10)),
                ('hotline', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('opening_hours', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('newsletter_code', models.CharField(blank=True, max_length=30)),
                ('newsletter_discount', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètres du site',
                'verbose_name_plural': 'paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('subject', models.CharField(choices=[('order', 'Commande'), ('product', 'Produit'), ('reseller', 'Devenir revendeur'), ('partnership', 'Partenariat'), ('other', 'Autre')], max_length=16, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'new'), ('handled', 'handled'), ('spam', 'spam')], db_index=True, default='new', max_length=8)),
                ('note', models.TextField(blank=True, verbose_name='note interne')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'abonné',
                'verbose_name_plural': 'abonnés',
                'ordering': ('-subscribed_at',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='content_subscriber_email_unique')],
            },
        ),
    ]
