# Generated by Django 5.2.17 on 2026-10-02 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sales_export', 'sales_export'), ('products_export', 'products_export'), ('products_import', 'products_import'), ('analytics_report', 'analytics_report')], max_length=24)),
                ('format', models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('pdf', 'pdf')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='pending', max_length=8)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('upload', models.BinaryField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=160)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tâche documentaire',
                'verbose_name_plural': 'tâches documentaires',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', '-created_at'], name='documents_job_owner')],
            },
        ),
    ]
