# Generated by Django 5.2.17 on 2026-10-02 20:22

import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('summarized_count', models.PositiveIntegerField(default=0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation assistant',
                'verbose_name_plural': 'conversations assistant',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10)),
                ('content', models.TextField()),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'positive'), ('neutral', 'neutral'), ('negative', 'negative')], max_length=10)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=60)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantsession')),
            ],
            options={
                'verbose_name': 'message assistant',
                'verbose_name_plural': 'messages assistant',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='catalog.product')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('embedded_text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=80)),
                ('category_slug', models.CharField(db_index=True, max_length=120)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vecteur produit',
                'verbose_name_plural': 'vecteurs produits',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='assistant_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['user', '-updated_at'], name='assistant_session_user'),
        ),
    ]
