# Generated by Django 5.2.17 on 2026-10-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('product_image', 'product_image'), ('category_image', 'category_image'), ('avatar', 'avatar'), ('message_attachment', 'message_attachment')], max_length=24)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('format', models.CharField(max_length=10)),
                ('bytes', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fichier',
                'verbose_name_plural': 'fichiers',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
