# Generated by Django 5.2.17 on 2026-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('actor_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ('-occurred_at',),
            },
        ),
    ]
