# Generated by Django 5.2.17 on 2026-10-02 16:59

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse e-mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='téléphone')),
                ('city', models.CharField(max_length=120, verbose_name='ville')),
                ('message', models.TextField(blank=True, verbose_name='motivation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=8, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('decision_note', models.CharField(blank=True, max_length=500, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçue le')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_applications', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidature revendeur',
                'verbose_name_plural': 'candidatures revendeur',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('status', 'pending')), name='resellers_application_single_pending')],
            },
        ),
    ]
