# Generated by Django 5.2.17 on 2026-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_sales_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFact',
            fields=[
                ('pk', models.CompositePrimaryKey('bucket', 'product_id', 'seller_id', 'payment_method', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField()),
                ('product_id', models.BigIntegerField()),
                ('category_id', models.BigIntegerField()),
                ('seller_id', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=24)),
                ('sales_count', models.IntegerField()),
                ('units', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costed_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'analytics_sales_fact',
                'managed': False,
            },
        ),
    ]
