# Generated by Django 5.2.17 on 2026-10-02 15:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_ts_config WHERE cfgname = 'french_unaccent'
                    ) THEN
                        CREATE TEXT SEARCH CONFIGURATION french_unaccent (COPY = french);
                        ALTER TEXT SEARCH CONFIGURATION french_unaccent
                            ALTER MAPPING FOR hword, hword_part, word
                            WITH unaccent, french_stem;
                    END IF;
                END
                $$;
            """,
            reverse_sql="DROP TEXT SEARCH CONFIGURATION IF EXISTS french_unaccent;",
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_product_search'),
        ),
    ]
