from dataclasses import dataclass, field
from decimal import Decimal

from apps.catalog.domain.enums import Badge, CategoryIcon


@dataclass(frozen=True, slots=True)
class DemoCategory:
    key: str
    name: str
    icon: CategoryIcon
    description: str
    color: tuple[str, str]


@dataclass(frozen=True, slots=True)
class DemoProduct:
    category: str
    name: str
    brand: str
    shape: str
    price: str
    cost: str
    stock: int
    description: str
    features: tuple[str, ...]
    sale_price: str | None = None
    badge: Badge | None = None
    free_shipping: bool = False
    options: dict[str, tuple[str, ...]] = field(default_factory=dict)
    variants: tuple[tuple[dict[str, str], str | None, int], ...] = ()

    @property
    def money(self) -> tuple[Decimal, Decimal | None, Decimal]:
        sale = Decimal(self.sale_price) if self.sale_price else None
        return Decimal(self.price), sale, Decimal(self.cost)


CATEGORIES = (
    DemoCategory(
        "smartphones",
        "Smartphones",
        CategoryIcon.MOBILE,
        "Les derniers smartphones Samsung, Apple, Xiaomi, Tecno et Infinix, neufs et garantis.",
        ("#1d4ed8", "#60a5fa"),
    ),
    DemoCategory(
        "tablettes",
        "Tablettes",
        CategoryIcon.TABLET,
        "Tablettes pour le travail, l'école et le divertissement.",
        ("#7c3aed", "#c4b5fd"),
    ),
    DemoCategory(
        "ordinateurs",
        "Ordinateurs portables",
        CategoryIcon.MONITOR,
        "Portables légers et puissants pour étudiants, entrepreneurs et créatifs.",
        ("#0f766e", "#5eead4"),
    ),
    DemoCategory(
        "audio",
        "Audio",
        CategoryIcon.HEADPHONE,
        "Écouteurs, casques et enceintes Bluetooth.",
        ("#b45309", "#fcd34d"),
    ),
    DemoCategory(
        "montres",
        "Montres connectées",
        CategoryIcon.WATCH,
        "Montres et bracelets connectés pour la santé et le sport.",
        ("#be123c", "#fda4af"),
    ),
    DemoCategory(
        "accessoires",
        "Accessoires",
        CategoryIcon.FLASH,
        "Chargeurs, câbles, batteries externes et protections.",
        ("#334155", "#94a3b8"),
    ),
    DemoCategory(
        "gaming",
        "Gaming",
        CategoryIcon.GAME,
        "Consoles et manettes pour jouer à la maison ou en déplacement.",
        ("#15803d", "#86efac"),
    ),
)

STORAGE = "Stockage"
COLOR = "Couleur"

PRODUCTS = (
    DemoProduct(
        "smartphones",
        "Samsung Galaxy A55 5G",
        "Samsung",
        "phone",
        "449.00",
        "355.00",
        25,
        'Écran Super AMOLED 6,6", triple caméra 50 Mpx et batterie 5000 mAh pour toute la journée.',
        (
            "Écran Super AMOLED 120 Hz",
            "Appareil photo 50 Mpx OIS",
            "Batterie 5000 mAh",
            "Résistant à l'eau IP67",
        ),
        sale_price="419.00",
        badge=Badge.BEST_SELLER,
        options={STORAGE: ("128 Go", "256 Go")},
        variants=(({STORAGE: "128 Go"}, None, 15), ({STORAGE: "256 Go"}, "489.00", 10)),
    ),
    DemoProduct(
        "smartphones",
        "Samsung Galaxy S24",
        "Samsung",
        "phone",
        "899.00",
        "740.00",
        8,
        "Le premier de la classe : processeur Snapdragon, IA Galaxy et appareil photo de nuit remarquable.",
        ("Écran Dynamic AMOLED 2X", "Galaxy AI", "Triple caméra 50 Mpx", "7 ans de mises à jour"),
        badge=Badge.NEW,
        free_shipping=True,
        options={COLOR: ("Noir", "Violet")},
        variants=(({COLOR: "Noir"}, None, 12), ({COLOR: "Violet"}, None, 8)),
    ),
    DemoProduct(
        "smartphones",
        "iPhone 15",
        "Apple",
        "phone",
        "999.00",
        "860.00",
        6,
        "Dynamic Island, port USB-C et appareil photo 48 Mpx dans un design en verre teinté.",
        ("Puce A16 Bionic", "Caméra principale 48 Mpx", "USB-C", "Dynamic Island"),
        free_shipping=True,
        options={STORAGE: ("128 Go", "256 Go")},
        variants=(({STORAGE: "128 Go"}, None, 10), ({STORAGE: "256 Go"}, "1099.00", 6)),
    ),
    DemoProduct(
        "smartphones",
        "Xiaomi Redmi Note 13",
        "Xiaomi",
        "phone",
        "229.00",
        "175.00",
        40,
        "Le meilleur rapport qualité-prix : écran AMOLED 120 Hz et charge rapide 33 W.",
        ("Écran AMOLED 120 Hz", "Caméra 108 Mpx", "Charge rapide 33 W", "Double SIM"),
        badge=Badge.BEST_SELLER,
    ),
    DemoProduct(
        "smartphones",
        "Tecno Spark 20 Pro",
        "Tecno",
        "phone",
        "189.00",
        "140.00",
        35,
        "Grand écran, gros son et belle autonomie à petit prix.",
        ('Écran 6,78" 120 Hz', "Caméra 108 Mpx", "Batterie 5000 mAh", "Haut-parleurs stéréo"),
        sale_price="169.00",
    ),
    DemoProduct(
        "smartphones",
        "Infinix Hot 40i",
        "Infinix",
        "phone",
        "129.00",
        "95.00",
        50,
        "Un smartphone fiable pour débuter, avec une batterie qui tient deux jours.",
        ('Écran 6,56" 90 Hz', "Batterie 5000 mAh", "Lecteur d'empreintes", "Mémoire 128 Go"),
    ),
    DemoProduct(
        "tablettes",
        "Samsung Galaxy Tab A9+",
        "Samsung",
        "tablet",
        "279.00",
        "215.00",
        18,
        'Une grande tablette 11" pour regarder, apprendre et travailler en famille.',
        ('Écran 11" 90 Hz', "Quatre haut-parleurs", "Mode Enfants", "Batterie 7040 mAh"),
        badge=Badge.NEW,
    ),
    DemoProduct(
        "tablettes",
        "iPad 10e génération",
        "Apple",
        "tablet",
        "499.00",
        "420.00",
        9,
        'Écran Liquid Retina 10,9", puce A14 et compatibilité Apple Pencil.',
        ('Écran Liquid Retina 10,9"', "Puce A14 Bionic", "Touch ID", "USB-C"),
        free_shipping=True,
    ),
    DemoProduct(
        "tablettes",
        "Lenovo Tab M10 Plus",
        "Lenovo",
        "tablet",
        "219.00",
        "165.00",
        14,
        "La tablette idéale pour les cours en ligne et le streaming.",
        ('Écran 2K 10,6"', "Son Dolby Atmos", "Mode lecture", "Batterie 7700 mAh"),
        sale_price="199.00",
    ),
    DemoProduct(
        "ordinateurs",
        "HP 15s Ryzen 5",
        "HP",
        "laptop",
        "649.00",
        "520.00",
        10,
        "Un portable polyvalent pour le bureau et les études, avec SSD rapide.",
        ("AMD Ryzen 5 7520U", "16 Go de RAM", "SSD 512 Go", 'Écran Full HD 15,6"'),
        badge=Badge.BEST_SELLER,
    ),
    DemoProduct(
        "ordinateurs",
        "Lenovo IdeaPad Slim 3",
        "Lenovo",
        "laptop",
        "579.00",
        "455.00",
        12,
        "Fin, léger et silencieux, il vous suit partout.",
        ("Intel Core i5 13e gén.", "8 Go de RAM", "SSD 512 Go", "1,6 kg"),
        sale_price="549.00",
    ),
    DemoProduct(
        "ordinateurs",
        "MacBook Air M2",
        "Apple",
        "laptop",
        "1199.00",
        "1020.00",
        4,
        "Puce M2, jusqu'à 18 h d'autonomie et un écran Liquid Retina éclatant.",
        ("Puce Apple M2", 'Écran Liquid Retina 13,6"', "18 h d'autonomie", "Sans ventilateur"),
        badge=Badge.NEW,
        free_shipping=True,
    ),
    DemoProduct(
        "ordinateurs",
        "Dell Latitude 3540",
        "Dell",
        "laptop",
        "799.00",
        "640.00",
        7,
        "Le portable professionnel robuste, prêt pour l'entreprise.",
        ("Intel Core i5", "16 Go de RAM", "SSD 512 Go", "Clavier rétroéclairé"),
    ),
    DemoProduct(
        "audio",
        "Samsung Galaxy Buds FE",
        "Samsung",
        "earbuds",
        "99.00",
        "68.00",
        30,
        "Réduction de bruit active et son puissant dans un format confortable.",
        (
            "Réduction de bruit active",
            "Jusqu'à 30 h avec le boîtier",
            "Bluetooth 5.2",
            "Résistant aux éclaboussures",
        ),
        sale_price="85.00",
        badge=Badge.BEST_SELLER,
    ),
    DemoProduct(
        "audio",
        "Apple AirPods (3e génération)",
        "Apple",
        "earbuds",
        "199.00",
        "160.00",
        12,
        "Audio spatial et autonomie jusqu'à 30 heures.",
        ("Audio spatial", "Boîtier MagSafe", "Résistants à l'eau", "Jusqu'à 30 h"),
    ),
    DemoProduct(
        "audio",
        "JBL Flip 6",
        "JBL",
        "speaker",
        "139.00",
        "98.00",
        20,
        "Une enceinte Bluetooth étanche au son JBL Original Pro.",
        ("Étanche IP67", "12 h d'autonomie", "PartyBoost", "Son JBL Original Pro"),
        options={COLOR: ("Noir", "Bleu", "Rouge")},
        variants=(
            ({COLOR: "Noir"}, None, 8),
            ({COLOR: "Bleu"}, None, 7),
            ({COLOR: "Rouge"}, None, 5),
        ),
    ),
    DemoProduct(
        "audio",
        "Sony WH-CH720N",
        "Sony",
        "headphone",
        "149.00",
        "110.00",
        9,
        "Casque sans fil léger avec réduction de bruit et 35 h d'autonomie.",
        ("Réduction de bruit", "35 h d'autonomie", "Appels mains libres", "192 g"),
        badge=Badge.NEW,
    ),
    DemoProduct(
        "montres",
        "Samsung Galaxy Watch6",
        "Samsung",
        "watch",
        "299.00",
        "230.00",
        10,
        "Suivi du sommeil, de la fréquence cardiaque et de vos séances de sport.",
        ("Écran Super AMOLED", "Suivi du sommeil", "GPS intégré", "Étanche 5 ATM"),
        sale_price="269.00",
    ),
    DemoProduct(
        "montres",
        "Xiaomi Smart Band 8",
        "Xiaomi",
        "band",
        "49.00",
        "32.00",
        45,
        "Le bracelet connecté au meilleur prix, 16 jours d'autonomie.",
        ('Écran AMOLED 1,62"', "150 modes sportifs", "16 jours d'autonomie", "Étanche 5 ATM"),
        badge=Badge.BEST_SELLER,
    ),
    DemoProduct(
        "montres",
        "Apple Watch SE",
        "Apple",
        "watch",
        "279.00",
        "230.00",
        6,
        "L'essentiel de l'Apple Watch : détection des chutes, suivi d'activité et notifications.",
        ("Détection des chutes", "Suivi d'activité", "Résistante à l'eau", "Puce S8"),
    ),
    DemoProduct(
        "accessoires",
        "Chargeur rapide Samsung 25 W",
        "Samsung",
        "charger",
        "29.00",
        "16.00",
        80,
        "Charge super rapide pour smartphones Galaxy et appareils USB-C.",
        ("25 W Super Fast Charging", "Port USB-C", "Protection contre la surchauffe"),
        badge=Badge.BEST_SELLER,
    ),
    DemoProduct(
        "accessoires",
        "Batterie externe Anker 20 000 mAh",
        "Anker",
        "powerbank",
        "49.00",
        "31.00",
        35,
        "Rechargez votre téléphone jusqu'à 4 fois, même pendant les coupures.",
        ("20 000 mAh", "Deux ports USB", "Charge rapide 20 W", "Témoin de charge"),
        sale_price="44.00",
    ),
    DemoProduct(
        "accessoires",
        "Câble USB-C tressé 2 m",
        "Baseus",
        "cable",
        "12.00",
        "5.00",
        120,
        "Un câble solide et long pour charger confortablement.",
        ("Tressé nylon", "2 mètres", "Charge rapide 60 W", "Transfert de données"),
    ),
    DemoProduct(
        "accessoires",
        "Coque silicone Galaxy A55",
        "Samsung",
        "case",
        "19.00",
        "8.00",
        60,
        "Une protection douce au toucher qui épouse parfaitement votre téléphone.",
        ("Silicone doux", "Bords surélevés", "Intérieur microfibre"),
        options={COLOR: ("Noir", "Lilas", "Vert")},
        variants=(
            ({COLOR: "Noir"}, None, 25),
            ({COLOR: "Lilas"}, None, 20),
            ({COLOR: "Vert"}, None, 15),
        ),
    ),
    DemoProduct(
        "gaming",
        "Manette sans fil Xbox",
        "Microsoft",
        "controller",
        "69.00",
        "50.00",
        15,
        "La manette Xbox pour console, PC et smartphone.",
        ("Bluetooth", "Prise jack 3,5 mm", "Partage en un bouton", "Compatible PC et mobile"),
    ),
    DemoProduct(
        "gaming",
        "Nintendo Switch OLED",
        "Nintendo",
        "console",
        "379.00",
        "320.00",
        5,
        'Jouez à la maison ou en déplacement sur un écran OLED de 7".',
        ('Écran OLED 7"', "64 Go de stockage", "Support réglable", "Son amélioré"),
        badge=Badge.NEW,
        free_shipping=True,
    ),
)
